<html lang="ja">
<head>
    <title><?php $this->block('title', '1') ?> - <?= $sitename ?></title>
</head>
<body>
<?php $this->begin('main') ?>
This is 1 body.
<?php $this->end() ?>

<?php $this->begin('block1') ?>extend1<?php $this->end() ?>

<?php $this->begin('block2') ?>extend1<?php $this->end() ?>

<?php $this->begin('block3') ?>extend1<?php $this->end() ?>

<?php $this->begin('block4') ?>extend1<?php $this->end() ?>

</body>
</html>
