<?php
# meta template data
// @formatter:off
// using variables:
/** @var \ryunosuke\NightDragon\Template $this */
/** @var mixed $_ */
/** @var integer $int */
/** @var boolean $bool */
/** @var double $both */
/** @var string $string */
/** @var string[] $array */
/** @var \Exception $object */
// @formatter:on
?>
<?= $null ?>
<?= $int ?>
<?= $bool ?>
<?= $both ?>
<?= $string | strtoupper ?>
<?= $array . x >> strtoupper ?>
<?= $array | implode(', ', $_) ?>
<?= $object->getMessage() ?>
<?= $parent1 ?>
