<?php
# meta template data
// @formatter:off
// using variables:
/** @var \ryunosuke\NightDragon\Template $this */
/** @var mixed $_ */
/** @var int $parent1 */
/** @var int $int */
/** @var bool $bool */
/** @var int|float $both */
/** @var string $string */
/** @var string[] $array */
/** @var \Exception $object */
/** @var string|int $hoge */
// @formatter:on
?>
<?= $null ?>
<?= $int ?>
<?= $bool ?>
<?= $both ?>
<?= $string | strtoupper ?>
<?= $array . x >> strtoupper ?>
<?= $array | implode(', ', $_) ?>
<?= $object->getMessage() ?>
<?= $parent1 ?>
<?= $hoge ?>
<?= $fuga ?>
