<?php
# meta template data
// @formatter:off
// using variables:
/** @var \ryunosuke\NightDragon\Template $this */
/** @var mixed $_ */
/** @var string $var1 */
/** @var string $var2 */
// using modifier functions:

// using array keys:

// @formatter:on
?>
<?php $this->begin('declare') ?>
<?php $this->end() ?>

<?= $var1 ?>
<?= $var2 ?>

<?php $this->include(__DIR__ . '/vars-inner.phtml') ?>
<?php $this->include(__DIR__ . '/vars-inner.phtml', ['inner1' => 'ex-inner1']) ?>
<?php $this->include(__DIR__ . '/vars-inner.phtml') ?>

<?php $this->import(__DIR__ . '/vars-inner.phtml') ?>
<?php $this->import(__DIR__ . '/vars-inner.phtml', ['inner2' => 'ex-inner2']) ?>
<?php $this->import(__DIR__ . '/vars-inner.phtml') ?>
