<?php
# meta template data
// @formatter:off
// using variables:
/** @var \ryunosuke\NightDragon\Template $this */
/** @var mixed $_ */
// using modifier functions:

// using array keys:

// @formatter:on
?>
<?php $this->extend(__DIR__ . '/vars-parent.phtml') ?>

<?php $this->begin('declare') ?>
<?php $this->assign('var1', 'ex-var1') ?>
<?php $this->assign('var2', 'ex-var2') ?>
<?php $this->end() ?>
